Library/Controllers/BooksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Library.Data;
using Library.Models;

namespace Library.Controllers
{
    public class BooksController : Controller
    {
        private readonly ApplicationDbContext _context;

        public BooksController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Books
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Books.Include(b => b.Author).Include(b => b.BookCopies);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Books/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = await _context.Books
                .Include(b => b.Author)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (book == null)
            {
                return NotFound();
            }

            return View(book);
        }

        // GET: Books/Create
        public IActionResult Create()
        {
            var authors = _context.Authors.Select(a => new
            {
                AuthorId = a.Id,
                FullName = a.FirstName + " " + a.SecondName
            }).ToList();

            ViewData["AuthorId"] = new SelectList(authors, "AuthorId", "FullName");
            return View();
        }

        // POST: Books/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,Year,AuthorId")] Book book)
        {
            if (ModelState.IsValid)
            {
                _context.Add(book);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["AuthorId"] = new SelectList(_context.Authors, "Id", "Id", book.AuthorId);
            return View(book);
        }

        // GET: Books/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = await _context.Books.FindAsync(id);
            if (book == null)
            {
                return NotFound();
            }

            var authors = _context.Authors.Select(a => new
            {
                AuthorId = a.Id,
                FullName = a.FirstName + " " + a.SecondName
            }).ToList();
            ViewData["AuthorId"] = new SelectList(authors, "AuthorId", "FullName");

            return View(book);
        }

        // POST: Books/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Year,AuthorId")] Book book)
        {
            if (id != book.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(book);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BookExists(book.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }

            var authors = _context.Authors.Select(a => new
            {
                AuthorId = a.Id,
                FullName = a.FirstName + " " + a.SecondName
            }).ToList();
            ViewData["AuthorId"] = new SelectList(authors, "AuthorId", "FullName");

            return View(book);
        }

        // GET: Books/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = await _context.Books
                .Include(b => b.Author)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (book == null)
            {
                return NotFound();
            }

            return View(book);
        }

        // POST: Books/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var pictures = _context.BookCopies
                .Where(b => b.BookId == id)
                .Include(b => b.Picture)
                .Select(b => b.Picture);

            var book = await _context.Books.FindAsync(id);

            _context.Books.Remove(book);
            _context.Pictures.RemoveRange(pictures);

            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        private bool BookExists(int id)
        {
            return _context.Books.Any(e => e.Id == id);
        }
    }
}

Library/Controllers/UsersController.cs
    using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Library.Models;
using Library.ViewModels;
using Library.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;

namespace Library.Controllers
{
    public class UsersController : Controller
    {
        private readonly UserManager<User> _userManager;
        private readonly ApplicationDbContext _context;

        public UsersController(UserManager<User> userManager, ApplicationDbContext context)
        {
            _userManager = userManager;
            _context = context;
        }

        [Authorize(Roles = "admin")]
        [HttpGet]
        public IActionResult Index() => View(_userManager.Users.ToList().Where(p => p.UserName != "admin"));

        [Authorize(Roles = "admin")]
        [HttpGet]
        public IActionResult CreateLibrarian()
        {
            return View("~/Views/Users/Create.cshtml", new ReaderViewModel { Role = "librarian" });

        }

        [Authorize(Roles = "admin")]
        [HttpGet]
        public IActionResult CreateReader() 
        {
            return View("~/Views/Users/Create.cshtml", new ReaderViewModel { Role = "reader" });
        }

        [Authorize(Roles = "admin")]
        [HttpPost]
        public async Task<IActionResult> Create(UserViewModel model)
        {
            if (ModelState.IsValid)
            {
                User user = new User { 
                    UserName = model.UserName,
                    FirstName = model.FirstName,
                    SecondName = model.SecondName
                };
                var result = await _userManager.CreateAsync(user, model.Password);

                if (result.Succeeded)
                {
                    if (model.Role.Equals("reader"))
                    {
                        Address address = new Address
                        {
                            City = model.City,
                            Street = model.Street,
                            Hous = model.Hous
                        };
                        Reader reader = new Reader
                        {
                            Id = user.Id,
                            AddressId = address.Id,
                            Phone = model.Phone
                        };

                        await _userManager.AddToRoleAsync(user, "reader");

                        _context.Addresses.Add(address);
                        _context.SaveChanges();
                        reader.AddressId = address.Id;
                        _context.Readers.Add(reader);
                        _context.SaveChanges();
                    }
                    else
                    {
                        Librarian librarian = new Librarian
                        {
                            Id = user.Id
                        };

                        await _userManager.AddToRoleAsync(user, "librarian");

                        _context.Librarians.Add(librarian);
                        _context.SaveChanges();
                    }

                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }
                }
            }
            return View(model);
        }

        [Authorize(Roles = "admin")]
        [HttpGet]
        public async Task<IActionResult> Edit(string id)
        {
            UserViewModel model;
            User user = await _userManager.FindByIdAsync(id);

            if (user == null)
            {
                return NotFound();
            }

            if (await _userManager.IsInRoleAsync(user, "reader"))
            {
                Reader reader = _context.Readers.Find(id);
                reader.Address = _context.Addresses.Find(reader.AddressId);

                model = new ReaderViewModel {
                    Id = user.Id,
                    UserName = user.UserName,
                    FirstName = user.FirstName,
                    SecondName = user.SecondName,
                    Phone = reader.Phone,
                    City = reader.Address.City,
                    Street = reader.Address.Street,
                    Hous = reader.Address.Hous,
                    Role = "reader"
                };
            }
            else
            {
                Librarian librarian = _context.Librarians.Find(id);

                model = new UserViewModel {
                    Id = user.Id,
                    UserName = user.UserName,
                    FirstName = user.FirstName,
                    SecondName = user.SecondName,
                    Role = "librarian"
                };
            }

            return View(model);
        }

        [Authorize(Roles = "admin")]
        [HttpPost]
        public async Task<IActionResult> Edit(UserViewModel model)
        {
            if (ModelState.IsValid)
            {
                User user = await _userManager.FindByIdAsync(model.Id);
                user.UserName = model.UserName;

                if (user != null)
                {
                    var result = await _userManager.UpdateAsync(user);

                    if (result.Succeeded)
                    {
                        user.FirstName = model.FirstName;
                        user.SecondName = model.SecondName;

                        if (model.Role.Equals("reader"))
                        {
                            Reader reader = _context.Readers.Find(model.Id);
                            reader.Address = _context.Addresses.Find(reader.AddressId);

                            
                            reader.Phone = model.Phone;
                            reader.Address.City = model.City;
                            reader.Address.Street = model.Street;
                            reader.Address.Hous = model.Hous;

                            _context.Readers.Update(reader);
                            await _context.SaveChangesAsync();
                        }
                        else
                        {
                            Librarian librarian = _context.Librarians.Find(model.Id);

                            _context.Librarians.Update(librarian);
                            await _context.SaveChangesAsync();
                        }
                    }
                    else
                    {
                        foreach (var error in result.Errors)
                        {
                            ModelState.AddModelError(string.Empty, error.Description);
                        }
                    }

                    return RedirectToAction("Index");
                }
            }

            return View(model);
        }

        [Authorize(Roles = "admin")]
        [HttpPost]
        public async Task<ActionResult> Delete(string id)
        {
            User user = await _userManager.FindByIdAsync(id);

            if (user != null)
            {
                if (await _userManager.IsInRoleAsync(user, "reader"))
                {
                    _context.Readers.Remove(_context.Readers.Find(id));
                }
                else
                {
                    _context.Librarians.Remove(_context.Librarians.Find(id));
                }

                IdentityResult result = await _userManager.DeleteAsync(user);
                await _context.SaveChangesAsync();
            }
            return RedirectToAction("Index");
        }
    }
}

Library/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Library</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Library</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Books" asp-action="Index">Книги</a>
                        </li>
                        @{
                            if (User.IsInRole("admin"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Index">Управление пользователями</a>
                                </li>
                            }
                            else if (User.IsInRole("librarian"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Usages" asp-action="Index">Контроль заказов</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Usages" asp-action="History">История заказов</a>
                                </li>
                            }
                            else if (User.IsInRole("reader"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Usages" asp-action="Index">Заказы</a>
                                </li>
                            }
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Library - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>